# Generated by Django 2.0.7 on 2018-07-08 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=events.models.default_start)),
                ('end', models.DateTimeField(default=events.models.default_end)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pads.Pad')),
            ],
        ),
    ]
