# Generated by Django 2.0.7 on 2018-07-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
