# Generated by Django 2.0.7 on 2018-10-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0006_ribbit_chain'),
        ('hoppers', '0011_auto_20181008_1609'),
        ('events', '0002_auto_20180709_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoppers.Hopper'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(related_name='invited', through='ribbits.Ribbit', to='hoppers.Hopper'),
        ),
    ]
