# Generated by Django 2.0.7 on 2018-10-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181008_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invitees',
        ),
    ]
