# Generated by Django 2.0.7 on 2018-10-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0008_auto_20181010_1600'),
        ('hoppers', '0011_auto_20181008_1609'),
        ('events', '0004_remove_event_invitees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(null=True, related_name='invited', through='ribbits.Ribbit', to='hoppers.Hopper'),
        ),
    ]
