# Generated by Django 2.0.7 on 2018-10-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181011_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending',
        ),
    ]
