# Generated by Django 2.0.7 on 2018-10-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending',
        ),
    ]
