# Generated by Django 2.0.7 on 2018-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
