# Generated by Django 2.0.7 on 2018-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ribbit',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ribbit',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
