# Generated by Django 2.0.7 on 2018-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0002_auto_20180821_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbit',
            name='title',
            field=models.CharField(default='_', max_length=200),
        ),
    ]
