# Generated by Django 2.0.7 on 2018-10-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0003_ribbit_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ribbit',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ribbit',
            name='got_by',
        ),
        migrations.RemoveField(
            model_name='ribbit',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='ribbit',
            name='title',
        ),
        migrations.AddField(
            model_name='ribbit',
            name='message',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
