# Generated by Django 2.0.7 on 2018-10-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0004_auto_20181004_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ribbit',
            name='message',
        ),
        migrations.AlterField(
            model_name='ribbit',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='hoppers.Hopper'),
        ),
    ]
