# Generated by Django 2.0.7 on 2018-10-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0005_auto_20181006_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbit',
            name='chain',
            field=models.TextField(null=True),
        ),
    ]
