# Generated by Django 2.0.7 on 2018-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0011_auto_20181008_1609'),
        ('events', '0003_auto_20181008_1609'),
        ('ribbits', '0006_ribbit_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ribbit',
            name='chain',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ribbit',
            unique_together={('sent_by', 'event')},
        ),
    ]
