# Generated by Django 2.0.7 on 2018-10-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_invitees'),
        ('hoppers', '0011_auto_20181008_1609'),
        ('ribbits', '0007_auto_20181009_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbit',
            name='sent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='hoppers.Hopper'),
        ),
        migrations.AlterUniqueTogether(
            name='ribbit',
            unique_together={('sent_by', 'sent_to', 'event')},
        ),
    ]
