# Generated by Django 2.0.7 on 2018-10-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_invitees'),
        ('hoppers', '0011_auto_20181008_1609'),
        ('ribbits', '0008_auto_20181010_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ribbit',
            options={'ordering': ['created_at']},
        ),

        migrations.AlterUniqueTogether(
            name='ribbit',
            unique_together={('sent_by', 'event')},
        ),
    ]
