# Generated by Django 2.0.7 on 2018-10-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0011_auto_20181008_1609'),
        ('events', '0007_auto_20181011_1241'),
        ('ribbits', '0010_auto_20181011_1257'),
    ]

    operations = [

        migrations.AlterUniqueTogether(
            name='ribbit',
            unique_together={('sent_by', 'event')},
        ),
    ]
