# Generated by Django 2.0.7 on 2018-10-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181011_1241'),
        ('hoppers', '0011_auto_20181008_1609'),
        ('ribbits', '0011_auto_20181011_1258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ribbit',
            unique_together={('sent_by', 'sent_to', 'event')},
        ),
    ]
