# Generated by Django 2.0.7 on 2018-10-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0014_auto_20181011_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ribbit',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='ribbit',
            name='response',
        ),
    ]
