# Generated by Django 2.0.7 on 2018-10-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0015_auto_20181011_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ribbit',
            options={'ordering': ['-created_at']},
        ),
    ]
