# Generated by Django 2.0.7 on 2018-10-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0011_auto_20181008_1609'),
        ('ribbits', '0017_auto_20181016_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbit',
            name='sent_to',
            field=models.ManyToManyField(related_name='sent_to', to='hoppers.Hopper'),
        ),
    ]
