# Generated by Django 2.0.7 on 2018-10-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0018_ribbit_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbit',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
