# Generated by Django 2.0.7 on 2018-10-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0002_auto_20181004_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopper',
            name='user',
        ),
    ]
