# Generated by Django 2.0.7 on 2018-10-05 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0004_hopper_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopper',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hopper',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hopper',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hopper',
            name='name',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hopper',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
