# Generated by Django 2.0.7 on 2018-10-05 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoppers', '0005_auto_20181004_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopper',
            name='listens_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
