# Generated by Django 2.0.7 on 2018-10-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0006_hopper_listens_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='hopper',
            name='listens_to',
        ),
        migrations.AddField(
            model_name='pairdata',
            name='first_hopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_hopper', to='hoppers.Hopper'),
        ),
        migrations.AddField(
            model_name='pairdata',
            name='second_hopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_hopper', to='hoppers.Hopper'),
        ),
        migrations.AddField(
            model_name='hopper',
            name='listens_to',
            field=models.ManyToManyField(through='hoppers.PairData', to='hoppers.Hopper'),
        ),
    ]
