# Generated by Django 2.0.7 on 2018-10-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0007_auto_20181004_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PairData',
            new_name='Pair',
        ),
    ]
