# Generated by Django 2.0.7 on 2018-10-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0008_auto_20181004_2229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('first_hopper', 'second_hopper')},
        ),
    ]
