# Generated by Django 2.0.7 on 2018-10-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0010_auto_20181006_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hopper',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='hopper',
            name='area',
        ),
    ]
