# Generated by Django 2.0.7 on 2018-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0011_auto_20181008_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopper',
            name='active',
        ),
        migrations.AlterField(
            model_name='hopper',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hopper',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
