# Generated by Django 2.0.7 on 2018-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0012_auto_20181102_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopper',
            name='excludes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hopper',
            name='includes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
