# Generated by Django 2.0.7 on 2019-08-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0013_auto_20181102_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
