# Generated by Django 5.1.15 on 2026-05-06 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ribbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('echo_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echoes', to='ribbits.ribbit')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ribbits', to='events.event')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_ribbits', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_ribbits', to=settings.AUTH_USER_MODEL)),
                ('spots', models.ManyToManyField(blank=True, related_name='spotted_ribbits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sent_by', 'event')},
            },
        ),
    ]
