# Generated by Django 2.0.7 on 2018-07-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0002_pad_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='owner',
        ),
        migrations.AddField(
            model_name='pad',
            name='name',
            field=models.CharField(default='My Pad', max_length=200),
        ),
        migrations.AddField(
            model_name='pad',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
