# Generated by Django 2.0.7 on 2018-07-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0003_auto_20180709_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
