# Generated by Django 2.0.7 on 2018-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0004_auto_20180709_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pad',
            name='name',
            field=models.CharField(default='My Pad', max_length=50),
        ),
    ]
