# Generated by Django 2.0.7 on 2018-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0005_auto_20180821_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
