# Generated by Django 2.0.7 on 2018-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0006_auto_20180821_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
