# Generated by Django 2.0.7 on 2018-10-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0007_auto_20180826_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
