# Generated by Django 2.0.7 on 2018-10-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoppers', '0011_auto_20181008_1609'),
        ('pads', '0008_auto_20181004_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoppers.Hopper'),
        ),
        migrations.AlterField(
            model_name='pad',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
