# Generated by Django 2.0.7 on 2018-10-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0009_auto_20181014_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='published_at',
        ),
    ]
