# Generated by Django 2.0.7 on 2018-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0010_remove_pad_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pad',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
