# Generated by Django 2.0.7 on 2018-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0011_auto_20181025_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
