# Generated by Django 2.0.7 on 2019-04-13 13:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0012_pad_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pad',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
