# Generated by Django 2.0.7 on 2019-04-19 12:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0013_auto_20190413_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
